name: PROD-Deploy verdant-mjml-server to aws elastic beanstalk
env:
  env: prod
  APP_NAME: mjml-server
  ENV_NAME: mjml-server-PROD
  PROJECT_NAME: mjml-server
  APP_VERSION_NAME: ${{ github.sha }}
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Generate CodeArtifact authentication token
        id: codeartifact
        run: |
          echo "::set-output name=auth_token::$(aws codeartifact get-authorization-token --domain verdant --domain-owner 525060412716 --region us-east-1 --query authorizationToken --output text)"

      - name: Build docker image from Dockerfile
        run: docker build -t 525060412716.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${env}

      - name: Configure AWS credentials
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 525060412716.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${env}

      - name: Push docker image to ECR
        run: docker push 525060412716.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${env}

      - name: Bundle docker compose and .ebextensions
        run: |
          zip -r $APP_VERSION_NAME.zip docker-compose.yml .ebextensions

      - name: Upload file to S3
        run: |
          aws s3 cp $APP_VERSION_NAME.zip s3://verdant-builds/$PROJECT_NAME/$PROJECT_NAME-$APP_VERSION_NAME.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: update the Application
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $APP_NAME \
            --version-label $APP_VERSION_NAME \
            --source-bundle S3Bucket=verdant-builds,S3Key=$PROJECT_NAME/$PROJECT_NAME-$APP_VERSION_NAME.zip \
            --region us-east-1

      - name: Deploy to Elastic Beanstalk
        run: |
            aws elasticbeanstalk update-environment \
            --description PROD \
            --application-name $APP_NAME \
            --environment-name $ENV_NAME \
            --version-label $APP_VERSION_NAME \
            --region us-east-1
